data:
  base_path: /Users/frederikmuthers/Git/piano-transformer # For training on the cluster: /hpcwork/lect0148
model:
  transformer_name: mistral-62M
  tokenizer_name: remi
  dataset_name: maestro
  version: 2
seed: 222