data:
  base_path: /Users/frederikmuthers/Git/piano-transformer # /work/lect0148 # For training on the cluster: /hpcwork/lect0148
model:
  transformer_name: mistral-155M
  tokenizer_name: remi
  dataset_name: aria
  version: 5.1
seed: 222
