data:
  base_path: /home/ty133885/project/data/aria-midi-deduped-genre # For training on the cluster: /hpcwork/lect0148
model:
  transformer_name: mistral-155M
  tokenizer_name: remi
  dataset_name: aria
  version: 5.1
seed: 222
